<?php
/**
 * @category    Genmato
 * @package     Genmato_RemboursInvoice
 * @copyright   Copyright (c) 2015 Genmato BV (https://genmato.com)
 */
?>
<?php if ($this->showInputForm()): ?>
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="po_number"><?php echo Mage::helper('genmato_remboursinvoice')->__(
                        'Purchase Order Number'
                    ) ?></label><br/>
                <input type="text" id="po_number" name="payment[po_number]"
                       title="<?php echo Mage::helper('genmato_remboursinvoice')->__("Purchase Order Number") ?>"
                       class="input-text" value="<?php echo $this->getInfoData('po_number') ?>"/>
            </div>
        </li>
    </ul>
<?php endif; ?>